name: 'Run ktlint and auto review'
description: 'Run ktlint for reviews'
author: 'minz.kweon@gmail.com'
inputs:
  ktlint_version:
    description: "To use ktlint version ('latest' or '0.44.0')"
    required: false
    default: 'latest'
  github_token:
    description: 'Github Token to create a review'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ktlint_version }}
    - ${{ inputs.github_token }}
branding:
  icon: 'check'
  color: 'purple'
