name: 'Run ktlint and auto review'
description: 'Run ktlint for reviews'
author: 'minz.kweon@gmail.com'
inputs:
  ktlint_version:
    description: "To use ktlint version ('latest' or '0.44.0')"
    required: false
    default: 'latest'
  github_token:
    description: 'Github Token to create a review'
    required: true
runs:
  using: 'composite'
  steps:
  - run: 'chmod a+x $GITHUB_ACTION_PATH/install.sh && $GITHUB_ACTION_PATH/install.sh'
    shell: bash
    env:
      KTLINT_VERSION: ${{ inputs.ktlint_version }} 
  - run: 'ktlint --reporter=checkstyle,output=report.xml'
    shell: bash
  - run: |
      ls -al
      pwd
    shell: bash
branding:
  icon: 'check'
  color: 'purple'